---
- name: Setup NTP and Cockpit on RHEL 9 System
  hosts: all
  become: true
  tasks:

    - name: Ensure chrony package is installed
      package:
        name: chrony
        state: present

    - name: Start and enable chronyd service
      systemd:
        name: chronyd
        state: started
        enabled: true

    - name: Configure NTP server to use north-america.pool.ntp.org
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        line: 'server north-america.pool.ntp.org iburst'
        create: yes

    - name: Restart chronyd service to apply changes
      systemd:
        name: chronyd
        state: restarted

    - name: Verify chronyd service is running
      systemd:
        name: chronyd
        state: started

    - name: Ensure cockpit package is installed
      package:
        name: cockpit-ws
        state: present

    - name: Start and enable cockpit service
      systemd:
        name: cockpit-ws
        state: started
        enabled: true

    - name: Open Cockpit port in the firewall
      firewalld:
        service: cockpit-ws
        permanent: true
        state: enabled
        immediate: yes

- name: Setup scheduled task to log cockpit service status
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the cron package is installed
      package:
        name: cron
        state: present

    - name: Create the script that queries the cockpit service status
      copy:
        dest: /usr/local/bin/check_cockpit_status.sh
        content: |
          #!/bin/bash
          # Check if cockpit service is running and append the status to the log
          if systemctl is-active --quiet cockpit; then
            echo "$(date) - Cockpit service is running" >> /var/log/automation.log
          else
            echo "$(date) - Cockpit service is not running" >> /var/log/automation.log
          fi
        mode: '0755'

    - name: Create a cron job for runningaway task
      cron:
        name: "runningaway"
        minute: "*/5"  # Every 5 minutes
        job: "/usr/local/bin/check_cockpit_status.sh"
        state: present

